class_name SpaceStation
extends Node3D
## Scenery: a Cornerian wheel station (models/space_station/, built by
## source/build_space_station.py). Solid, but not shootable: it's friendly.
##
## At load it cel-shades the imported model (ToonMaterial), makes its hull
## collide on the World layer (so you crash into it, bolts stop on it and it
## blocks line of sight) and covers it with ObstacleProxy spheres so the AI
## steers round its real shape. Other systems keep clear of it through
## overlaps() / push_clear(): the asteroid field, wave spawns and the
## destroyer's arrival. They find it through the `station` group.

## AI avoidance spheres (x, y, z, radius) in this node's space. Generated by
## build_space_station.py into proxies.txt: paste that line here after
## changing the model's layout.
@export var proxies: Array[Vector4] = []
## Materials (by name) left out of the collision: small lights and windows
## that would add thousands of triangles and nothing to crash into.
@export var non_solid_materials: PackedStringArray = [
	"Station_Window", "Station_HangarGlow", "Station_NavRed", "Station_NavGreen", "Station_NavWhite"]

var _proxies: Array[ObstacleProxy] = []


func _enter_tree() -> void:
	add_to_group("station")


func _ready() -> void:
	ToonMaterial.convert_tree($Model)
	_build_collision()
	for sphere in proxies:
		var proxy := ObstacleProxy.new()
		proxy.radius = sphere.w
		proxy.position = Vector3(sphere.x, sphere.y, sphere.z)
		add_child(proxy)
		_proxies.append(proxy)


## True if a sphere of `sphere_radius` at `point` comes within `margin` of the
## station (its avoidance spheres).
func overlaps(point: Vector3, sphere_radius: float, margin := 0.0) -> bool:
	for proxy in _proxies:
		if proxy.global_position.distance_to(point) < proxy.radius + sphere_radius + margin:
			return true
	return false


## `point` moved out of every avoidance sphere it's within `margin` of, the
## same way AIPilot._clear_of_obstacles() moves waypoints. Two passes, since
## pushing out of one sphere can land in a neighbour.
func push_clear(point: Vector3, margin: float) -> Vector3:
	for pass_index in 2:
		for proxy in _proxies:
			var clearance := proxy.radius + margin
			var offset := point - proxy.global_position
			if offset.length() < clearance:
				var push := offset.normalized() if offset.length() > 0.1 else Vector3.UP
				point = proxy.global_position + push * clearance
	return point


## Radius of a sphere round the station's origin that holds all of it.
func bounding_radius() -> float:
	var reach := 0.0
	for sphere in proxies:
		reach = maxf(reach, Vector3(sphere.x, sphere.y, sphere.z).length() + sphere.w)
	return reach


## One trimesh collision shape per component, from its solid surfaces.
func _build_collision() -> void:
	var body := StaticBody3D.new()
	body.name = "Collision"
	body.collision_layer = Fighter.LAYER_WORLD
	body.collision_mask = 0
	add_child(body)
	for node in $Model.find_children("*", "MeshInstance3D", true, false):
		var mesh_instance := node as MeshInstance3D
		var faces := PackedVector3Array()
		for surface in mesh_instance.mesh.get_surface_count():
			var material := mesh_instance.mesh.surface_get_material(surface)
			if material and material.resource_name in non_solid_materials:
				continue
			var arrays := mesh_instance.mesh.surface_get_arrays(surface)
			var vertices: PackedVector3Array = arrays[Mesh.ARRAY_VERTEX]
			var indices: PackedInt32Array = arrays[Mesh.ARRAY_INDEX]
			if indices.is_empty():
				faces.append_array(vertices)
			else:
				for index in indices:
					faces.append(vertices[index])
		if faces.is_empty():
			continue
		var shape := ConcavePolygonShape3D.new()
		shape.set_faces(faces)
		var collision := CollisionShape3D.new()
		collision.name = mesh_instance.name
		collision.shape = shape
		body.add_child(collision)
		collision.global_transform = mesh_instance.global_transform
